/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArbreRouteImport } from './routes/arbre'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as TemoinRouteImport } from './routes/temoin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArbreRoute = ArbreRouteImport.update({
  id: '/arbre',
  path: '/arbre',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const TemoinRoute = TemoinRouteImport.update({
  id: '/temoin',
  path: '/temoin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arbre': typeof ArbreRoute
  '/guide': typeof GuideRoute
  '/journal': typeof JournalRoute
  '/temoin': typeof TemoinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arbre': typeof ArbreRoute
  '/guide': typeof GuideRoute
  '/journal': typeof JournalRoute
  '/temoin': typeof TemoinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arbre': typeof ArbreRoute
  '/guide': typeof GuideRoute
  '/journal': typeof JournalRoute
  '/temoin': typeof TemoinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/arbre' | '/guide' | '/journal' | '/temoin'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/arbre' | '/guide' | '/journal' | '/temoin'
  id: '__root__' | '/' | '/arbre' | '/guide' | '/journal' | '/temoin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArbreRoute: typeof ArbreRoute
  GuideRoute: typeof GuideRoute
  JournalRoute: typeof JournalRoute
  TemoinRoute: typeof TemoinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arbre': {
      id: '/arbre'
      path: '/arbre'
      fullPath: '/arbre'
      preLoaderRoute: typeof ArbreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temoin': {
      id: '/temoin'
      path: '/temoin'
      fullPath: '/temoin'
      preLoaderRoute: typeof TemoinRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArbreRoute: ArbreRoute,
  GuideRoute: GuideRoute,
  JournalRoute: JournalRoute,
  TemoinRoute: TemoinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
