/**
 * Lexique des hôtes — les voix de la Tour, écrites une fois.
 *
 * Neuf muses. Pour chacune : un rôle majeur, trois rôles mineurs (les
 * familiers), vingt-sept répliques en trois groupes de neuf (accueil,
 * demande, don), et douze noms de capture. FR et EN, même nombre partout.
 *
 * Ton : une phrase, un verbe, une règle vraie. Chaque réplique cite quelque
 * chose que le code fait — même norme à chaque palier, une clé signe une
 * fois, le rendu sous dix mille atomes devient frais. Aucun oracle, aucun
 * lore neuf : les hôtes disent ce qui est.
 *
 * L'hôte choisit ses trois répliques par sa graine (hotes.ts) ; le nom d'une
 * capture se lit dans son mot (capsules.ts). Le lexique est une jauge : le
 * changer ne change ni un mot ni une graine.
 *
 * LIMITE : les noms de capture sont des noms communs français, identiques en
 * anglais — un nom est une jauge, l'identité est le mot.
 */

import type { SignatureId } from "./signatures.ts";

export type LangueHote = "fr" | "en";

export const REPLIQUES_PAR_GROUPE = 9;
export const GROUPES_REPLIQUES = ["accueil", "demande", "don"] as const;
export type GroupeReplique = (typeof GROUPES_REPLIQUES)[number];
export const REPLIQUES_PAR_MUSE = REPLIQUES_PAR_GROUPE * GROUPES_REPLIQUES.length;
export const NOMS_PAR_MUSE = 12;

export type Bilingue = { fr: string; en: string };

export type RolesMuse = {
  majeur: Bilingue;
  mineurs: readonly [Bilingue, Bilingue, Bilingue];
};

/** Les neuf rôles, de la Terre au faîte. */
export const ROLES: Record<SignatureId, RolesMuse> = {
  terre: {
    majeur: { fr: "l'aubergiste", en: "the innkeeper" },
    mineurs: [
      { fr: "le marmiton", en: "the kitchen boy" },
      { fr: "la servante d'auberge", en: "the inn maid" },
      { fr: "le veilleur du sol", en: "the ground watchman" },
    ],
  },
  lune: {
    majeur: { fr: "l'archiviste", en: "the archivist" },
    mineurs: [
      { fr: "le copiste", en: "the copyist" },
      { fr: "la greffière", en: "the clerk" },
      { fr: "le relieur", en: "the bookbinder" },
    ],
  },
  mercure: {
    majeur: { fr: "l'apothicaire", en: "the apothecary" },
    mineurs: [
      { fr: "l'herboriste", en: "the herbalist" },
      { fr: "le commis d'officine", en: "the dispensary boy" },
      { fr: "la préparatrice", en: "the compounder" },
    ],
  },
  venus: {
    majeur: { fr: "la maîtresse de danse", en: "the dancing mistress" },
    mineurs: [
      { fr: "le ménétrier", en: "the fiddler" },
      { fr: "la figurante", en: "the walk-on dancer" },
      { fr: "le maître à danser", en: "the dancing master" },
    ],
  },
  soleil: {
    majeur: { fr: "la tragédienne", en: "the tragedienne" },
    mineurs: [
      { fr: "le choriste", en: "the chorister" },
      { fr: "la coryphée", en: "the coryphaeus" },
      { fr: "le porteur de masque", en: "the mask bearer" },
    ],
  },
  mars: {
    majeur: { fr: "la forgeronne", en: "the smith" },
    mineurs: [
      { fr: "l'apprenti forgeron", en: "the smith's apprentice" },
      { fr: "la souffleuse", en: "the bellows girl" },
      { fr: "le ferrailleur", en: "the scrap dealer" },
    ],
  },
  jupiter: {
    majeur: { fr: "la musicienne", en: "the musician" },
    mineurs: [
      { fr: "le joueur d'aulos", en: "the aulos player" },
      { fr: "la chanteuse", en: "the singer" },
      { fr: "l'accordeur", en: "the tuner" },
    ],
  },
  saturne: {
    majeur: { fr: "la gardienne des hymnes", en: "the keeper of hymns" },
    mineurs: [
      { fr: "le portier", en: "the gatekeeper" },
      { fr: "la lectrice d'hymnes", en: "the hymn reader" },
      { fr: "le sonneur", en: "the bell ringer" },
    ],
  },
  uranie: {
    majeur: { fr: "l'astronome", en: "the astronomer" },
    mineurs: [
      { fr: "le guetteur", en: "the lookout" },
      { fr: "la calculatrice", en: "the computer" },
      { fr: "le porteur de lunette", en: "the telescope bearer" },
    ],
  },
};

export type RepliquesMuse = Record<LangueHote, Record<GroupeReplique, readonly string[]>>;

/** 27 répliques par muse et par langue : 9 d'accueil, 9 de demande, 9 de don. */
export const REPLIQUES: Record<SignatureId, RepliquesMuse> = {
  terre: {
    fr: {
      accueil: [
        "Entrez : la ville est le coffre, la Tour commence ici.",
        "Le réseau d'essai n'a aucune valeur ; asseyez-vous quand même.",
        "Cent une formes, jamais un stock : chacun tire la sienne.",
        "Terre au sol, Uranie au faîte ; entre les deux, même norme.",
        "Le robinet verse un eidôlon sur une adresse neuve, pas un de plus.",
        "Un objet tiré avant l'équipement reste une trouvaille : son mot ne change pas.",
        "Deux maîtres, même bloc : deux objets ; personne ne prend le vôtre.",
        "Ici on crée des blocs, on tire des objets, on sertit ; là-haut on lit.",
        "L'auberge ne mine pas : la Tour non plus.",
      ],
      demande: [
        "Je ne demande rien : on accueille, on ne tarife pas.",
        "Rien à payer : le poste du jour se compte, il ne se vend pas.",
        "Gardez vos pièces : trois entrées au plus par envoi, et l'auberge n'en est pas une.",
        "Ne me tendez pas de preuve : je ne juge pas, je sers.",
        "Aucune demande ; un tirage par hauteur, c'est le seul rythme que j'impose.",
        "Rien : le rendu sous dix mille atomes devient frais, ce serait dommage.",
        "Ne signez rien ici : une clé signe une fois, épargnez-la.",
        "Je ne veux rien ; le quatrième bloc du jour attendra demain.",
        "Pas de mise à l'auberge : les sceaux se trouvent, ils ne s'achètent pas.",
      ],
      don: [
        "Trois blocs par jour : voilà votre poste, et voilà du sel.",
        "Du sel au premier passage : une résonance destructive s'y lit neutre, un étage durant.",
        "Trois blocs créés, une capsule vide : un glyphe creux pour un occupant.",
        "Le sel tient ce qui ne se divise pas ; buvez-le à l'étage qu'il faut.",
        "Un élixir se boit une fois ; son mot est noté, jamais repris.",
        "Le poste du jour vaut trois ; le compte se remet à zéro à minuit civil.",
        "Prenez la capsule : vide, elle ne fait rien ; pleine, elle garde le mot de l'occupant.",
        "Le sel ne touche ni la norme ni les axes : il lit autrement, c'est tout.",
        "Montez : le premier palier ne rend pas plus fort, aucun ne le fera.",
      ],
    },
    en: {
      accueil: [
        "Come in: the city is the vault, the Tower starts here.",
        "The test network has no value; sit down all the same.",
        "One hundred and one forms, never a stock: each draws their own.",
        "Earth at the ground, Urania at the peak; between them, the same norm.",
        "The faucet pours one eidolon onto a fresh address, not one more.",
        "An item drawn before equipment stays a find: its word does not change.",
        "Two masters, same block: two items; nobody takes yours.",
        "Here we make blocks, draw items, set stones; up there we read.",
        "The inn does not mine: neither does the Tower.",
      ],
      demande: [
        "I ask for nothing: we welcome, we do not charge.",
        "Nothing to pay: the day's post is counted, not sold.",
        "Keep your coins: three inputs at most per send, and the inn is not one.",
        "Do not hand me a proof: I do not judge, I serve.",
        "No request; one draw per height is the only rhythm I impose.",
        "Nothing: change under ten thousand atoms becomes fee, that would be a waste.",
        "Sign nothing here: a key signs once, spare it.",
        "I want nothing; the day's fourth block will wait for tomorrow.",
        "No stake at the inn: seals are found, never bought.",
      ],
      don: [
        "Three blocks a day: that is your post, and here is salt.",
        "Salt on your first pass: a destructive resonance reads neutral there, one floor long.",
        "Three blocks made, one empty capsule: a hollow glyph for an occupant.",
        "Salt holds what does not divide; drink it on the floor that needs it.",
        "An elixir is drunk once; its word is noted, never taken back.",
        "The day's post is three; the count resets at civil midnight.",
        "Take the capsule: empty, it does nothing; full, it keeps the occupant's word.",
        "Salt touches neither the norm nor the axes: it reads differently, that is all.",
        "Climb: the first floor does not make you stronger, none will.",
      ],
    },
  },
  lune: {
    fr: {
      accueil: [
        "Rien ne se croit, tout se rejoue : bienvenue aux archives.",
        "Le carnet n'est jamais persisté ; il se reconstruit à chaque ouverture.",
        "Je lis votre historique à voix haute ; je n'y ajoute rien.",
        "Un bloc porte sa racine ; la racine déclarée doit être la racine calculée.",
        "Une époque compte mille huit blocs et somme exactement a fois T.",
        "Ce que la Tour note vit dans la jauge, hors feuille : perdre la jauge ne perd rien.",
        "Un objet ne mute pas : le mot est une identité, l'archive n'a rien à corriger.",
        "Une graine de relique n'existe que dans son QR ; l'archive n'en garde aucune.",
        "La tête signée dit hauteur, validateur, racine : de quoi juger sans rejouer.",
      ],
      demande: [
        "Montrez-moi une preuve d'inclusion d'une de vos pièces : le Journal la donne.",
        "Une pièce, sa preuve contre la racine du bloc : c'est tout ce que je lis.",
        "Pas votre solde : une pièce prouvée, une seule.",
        "La preuve se juge contre la racine signée, sans rejouer ; apportez-la.",
        "Une pièce et son chemin de Merkle ; l'ordre est (txid, rang), je n'en accepte pas d'autre.",
        "Une feuille : txid, rang, adresse, montant, hachés deux fois.",
        "Apportez une pièce qui tient dans un bloc scellé de votre coffre.",
        "Je demande une preuve, pas une figure : les figures ne prouvent rien.",
        "Une inclusion, pas une promesse : le carnet ne croit personne.",
      ],
      don: [
        "Du sel : une résonance destructive se lit neutre, un étage durant.",
        "Voici du sel ; votre historique, je le garde en lecture, jamais en preuve.",
        "Du sel pour l'étage ; le mot de la fiole est noté, il ne servira qu'une fois.",
        "Prenez le sel : il tient ce qui ne se divise pas.",
        "Un élixir, un étage, puis jeté ; l'archive note le mot bu.",
        "Du sel, et cette lecture : chaque envoi de votre Journal a rejoué à l'octet près.",
        "Le sel ne réécrit aucun mot ; rien dans mes registres ne bouge.",
        "Sel : la stabilité, pas la force ; la norme reste ce qu'elle est.",
        "Voici le sel ; le reste, vous le rejouerez vous-même.",
      ],
    },
    en: {
      accueil: [
        "Nothing is believed, everything is replayed: welcome to the archives.",
        "The ledger is never persisted; it is rebuilt at every opening.",
        "I read your history aloud; I add nothing to it.",
        "A block carries its root; the declared root must be the computed root.",
        "An epoch counts one thousand and eight blocks and sums exactly a times T.",
        "What the Tower notes lives in the gauge, off-sheet: losing the gauge loses nothing.",
        "An item does not mutate: the word is an identity, the archive has nothing to correct.",
        "A relic seed exists only in its QR; the archive keeps none.",
        "The signed head states height, validator, root: enough to judge without replaying.",
      ],
      demande: [
        "Show me an inclusion proof for one of your coins: the Journal gives it.",
        "One coin, its proof against the block root: that is all I read.",
        "Not your balance: one proven coin, only one.",
        "The proof is judged against the signed root, without replaying; bring it.",
        "One coin and its Merkle path; the order is (txid, rank), I accept no other.",
        "One leaf: txid, rank, address, amount, hashed twice.",
        "Bring a coin that sits in a sealed block of your vault.",
        "I ask for a proof, not a figure: figures prove nothing.",
        "An inclusion, not a promise: the ledger believes no one.",
      ],
      don: [
        "Salt: a destructive resonance reads neutral, one floor long.",
        "Here is salt; your history I keep as a reading, never as a proof.",
        "Salt for the floor; the vial's word is noted, it will serve only once.",
        "Take the salt: it holds what does not divide.",
        "One elixir, one floor, then discarded; the archive notes the word drunk.",
        "Salt, and this reading: every send in your Journal replayed to the byte.",
        "Salt rewrites no word; nothing in my registers moves.",
        "Salt: stability, not strength; the norm stays what it is.",
        "Here is the salt; the rest you will replay yourself.",
      ],
    },
  },
  mercure: {
    fr: {
      accueil: [
        "Conjuguer ne change pas l'orbite : g q ḡ garde l'angle de q.",
        "Le conjugué inverse le chemin ; la norme est conservée.",
        "A·B n'est pas B·A : l'ordre change l'issue.",
        "Trois espèces, les trois étages d'un glyphe : sel, mercure, soufre.",
        "Un élixir est un objet comme un autre : un mot, un archétype, un âge.",
        "Même orbite, au grain de la lecture : la première figure du mot.",
        "Une pierre tourne un mot en un autre mot ; rien n'est réécrit.",
        "Aucun élixir ne touche la norme ni les axes de combat.",
        "L'officine ne vend pas : un élixir se reçoit, d'un hôte, d'une alcôve, d'un écho.",
      ],
      demande: [
        "Deux objets de même orbite : même première figure, je les lis d'un coup d'œil.",
        "Apportez deux mots dont l'angle se lit pareil ; l'axe, je m'en moque.",
        "Deux objets, une orbite : tournez-en un avec une pierre si nécessaire.",
        "Même orbite, pas même mot : deux identités, une seule classe d'angle.",
        "Deux mots qui se conjuguent l'un en l'autre ; l'orbite en est le signe.",
        "Apportez la paire dont les premières figures coïncident.",
        "Deux objets : la Tour lit quatre figures d'angle, montrez-m'en deux égales.",
        "Une pierre T à gauche ou S à droite change l'angle ; accordez, puis revenez.",
        "Deux mots de même orbite ; je ne compte ni l'âge ni l'archétype.",
      ],
      don: [
        "Du mercure : la parade est accordée d'office, au deuxième temps du duel.",
        "Voici le mercure ; il se boit à un étage, et l'effet n'en sort pas.",
        "Mercure : la mobilité, la conjugaison qui déplace l'axe.",
        "Prenez le mercure ; un élixir bu est noté par son mot, jamais rebu.",
        "Du mercure pour une capture : accordée par l'objet porté, elle devient une autre capture.",
        "Le mercure accorde, il ne fusionne pas : aucun niveau, aucune somme.",
        "Une fiole ☽ ; l'espèce se lit à l'étage dominant de son glyphe.",
        "Du mercure ; il ne touche ni la norme ni les axes, seulement la lecture.",
        "Mercure : un étage, puis jeté ; gardez la pierre pour la prochaine orbite.",
      ],
    },
    en: {
      accueil: [
        "Conjugating does not change the orbit: g q ḡ keeps the angle of q.",
        "The conjugate reverses the path; the norm is conserved.",
        "A·B is not B·A: the order changes the outcome.",
        "Three species, the three floors of a glyph: salt, mercury, sulphur.",
        "An elixir is an item like any other: a word, an archetype, an age.",
        "Same orbit, at the grain of the reading: the word's first figure.",
        "A stone turns a word into another word; nothing is rewritten.",
        "No elixir touches the norm or the combat axes.",
        "The dispensary does not sell: an elixir is received, from a host, an alcove, an echo.",
      ],
      demande: [
        "Two items of the same orbit: same first figure, I read them at a glance.",
        "Bring two words whose angle reads alike; the axis I care not for.",
        "Two items, one orbit: turn one with a stone if you must.",
        "Same orbit, not same word: two identities, one angle class.",
        "Two words that conjugate into each other; the orbit is the sign.",
        "Bring the pair whose first figures coincide.",
        "Two items: the Tower reads four angle figures, show me two equal ones.",
        "A T stone on the left or an S on the right changes the angle; tune, then return.",
        "Two words of the same orbit; I count neither age nor archetype.",
      ],
      don: [
        "Mercury: the parry is granted outright, on the duel's second beat.",
        "Here is mercury; it is drunk on one floor, and the effect does not leave it.",
        "Mercury: mobility, the conjugation that moves the axis.",
        "Take the mercury; a drunk elixir is noted by its word, never drunk again.",
        "Mercury for a capture: tuned by the worn item, it becomes another capture.",
        "Mercury tunes, it does not fuse: no level, no sum.",
        "A ☽ vial; the species reads at the dominant floor of its glyph.",
        "Mercury; it touches neither norm nor axes, only the reading.",
        "Mercury: one floor, then discarded; keep the stone for the next orbit.",
      ],
    },
  },
  venus: {
    fr: {
      accueil: [
        "Même classe : destructif ; la distance angulaire décide du reste.",
        "Constructif quand deux fois le carré de l'alignement dépasse le produit des normes.",
        "La tenue est une lecture : la somme des accords moins la somme des heurts.",
        "Une gemme s'enchâsse sans toucher le mot.",
        "Deux alvéoles au plus par pièce.",
        "Neuf danses, une par muse, sur une période de onze secondes trois dixièmes.",
        "Une paire n'est pas une table de sets : elle se lit, elle ne se combine pas.",
        "Les occupants d'un étage s'interfèrent : même classe, même heurt.",
        "Ici on danse à deux ; l'ensemble, c'est chez la musicienne.",
      ],
      demande: [
        "Une paire en résonance constructive : deux objets de classes différentes, bien alignés.",
        "Apportez deux mots dont l'alignement tient : constructif, pas neutre.",
        "Une paire constructive ; même classe serait un heurt, je n'en veux pas.",
        "Deux objets dont le carré de l'alignement, doublé, dépasse le produit des normes.",
        "Une capture en résonance constructive avec l'objet porté, je la prends aussi.",
        "Deux danseurs accordés : classes distinctes, angles proches.",
        "Montrez-moi une paire dont la lecture dit constructif, rien de moins.",
        "Une paire : je lis le produit scalaire, pas le nom.",
        "L'offrande d'une capture vaut la paire ; elle quitte le coffre, rien n'est gravé.",
      ],
      don: [
        "Une gemme : elle s'enchâsse, le mot de la pièce reste intact.",
        "Voici une gemme ; deux alvéoles au plus, choisissez la pièce.",
        "Une gemme : la lecture composée change, l'identité non.",
        "Prenez la gemme ; enchâssée, elle tourne la lecture, jamais le mot.",
        "Une gemme, pour une paire qui tient ; la tenue s'est lue, elle ne se garde pas.",
        "Gemme : un affixe T ou S, lu en composition, retiré sans trace.",
        "Une gemme contre une capture offerte ; la capture est retirée, rien n'est gravé.",
        "Voici la gemme ; avec du sel et la forgeronne, elle devient une capsule.",
        "Une gemme ; la cage du coffre précieux en compte les éclats, le carnet non.",
      ],
    },
    en: {
      accueil: [
        "Same class: destructive; the angular distance decides the rest.",
        "Constructive when twice the square of the alignment exceeds the product of the norms.",
        "Hold is a reading: the sum of accords minus the sum of clashes.",
        "A gem is set without touching the word.",
        "Two sockets at most per piece.",
        "Nine dances, one per muse, over a period of eleven seconds and three tenths.",
        "A pair is not a set table: it is read, it is not combined.",
        "The occupants of a floor interfere: same class, same clash.",
        "Here we dance in pairs; the ensemble is the musician's.",
      ],
      demande: [
        "A pair in constructive resonance: two items of different classes, well aligned.",
        "Bring two words whose alignment holds: constructive, not neutral.",
        "A constructive pair; same class would be a clash, I want none.",
        "Two items whose squared alignment, doubled, exceeds the product of the norms.",
        "A capture in constructive resonance with the worn item, I take it too.",
        "Two tuned dancers: distinct classes, close angles.",
        "Show me a pair whose reading says constructive, nothing less.",
        "A pair: I read the dot product, not the name.",
        "The offering of a capture counts as the pair; it leaves the vault, nothing is engraved.",
      ],
      don: [
        "A gem: it is set, the piece's word stays intact.",
        "Here is a gem; two sockets at most, choose the piece.",
        "A gem: the composed reading changes, the identity does not.",
        "Take the gem; set, it turns the reading, never the word.",
        "A gem, for a pair that holds; the hold was read, it is not kept.",
        "Gem: a T or S affix, read in composition, removed without trace.",
        "A gem for an offered capture; the capture is removed, nothing is engraved.",
        "Here is the gem; with salt and the smith, it becomes a capsule.",
        "A gem; the precious vault's cage counts its sparks, the ledger does not.",
      ],
    },
  },
  soleil: {
    fr: {
      accueil: [
        "Aucun point de vie : un combat se lit, il ne se soustrait pas.",
        "Repoussé d'un étage : rien de perdu, rien de gravé.",
        "Une capsule brisée est retirée ; l'occupant, lui, reste.",
        "Le soufre transmute une fois : une pierre tourne sans forgeronne.",
        "Un objet extrême n'est pas plus fort ; il est plus pointu.",
        "Les quatre axes somment soixante-quatre, toujours.",
        "L'âge est une géographie, pas une puissance.",
        "Monter ne rend pas plus fort ; on lit mieux.",
        "L'état de combat est éphémère : on le jette.",
      ],
      demande: [
        "Un objet de la classe de cet étage : l'archétype du biome, rien d'autre.",
        "Apportez un mot dont l'archétype est celui de la bande.",
        "Un objet du biome ; sa classe se lit, elle ne se déclare pas.",
        "Un seul objet, de la classe des occupants : même muse qu'eux.",
        "La classe de l'étage, dans votre coffre ; l'âge m'indiffère.",
        "Un objet dont la muse est celle de la bande : je le reconnais à l'archétype.",
        "Montrez un mot de la maison ; ici la maison est une classe.",
        "Un objet de cette classe : la tragédie veut son chœur.",
        "Apportez la classe du biome ; une capture de cette classe fait aussi l'affaire.",
      ],
      don: [
        "Du soufre : une pierre tourne une pièce sans forgeronne, une fois.",
        "Voici le soufre ; la transmutation, c'est le craft existant, ni plus ni moins.",
        "Soufre : il se boit à un étage, l'effet s'y tient, puis la fiole est jetée.",
        "Prenez le soufre ; le mot de la pièce tournée est un autre mot, l'ancien n'est pas réécrit.",
        "Du soufre ; une fois bu, son mot est noté et ne revient pas.",
        "Une fiole ✚ ; l'espèce est l'étage dominant de son glyphe.",
        "Soufre : la pierre est consommée, la pièce devient une autre pièce.",
        "Du soufre ; ni la norme ni les axes n'en sont touchés.",
        "Le soufre transmute ; il ne multiplie rien.",
      ],
    },
    en: {
      accueil: [
        "No hit points: a fight is read, it is not subtracted.",
        "Pushed back one floor: nothing lost, nothing engraved.",
        "A broken capsule is removed; the occupant stays.",
        "Sulphur transmutes once: a stone turns without the smith.",
        "An extreme item is not stronger; it is sharper.",
        "The four axes sum to sixty-four, always.",
        "Age is a geography, not a power.",
        "Climbing does not make you stronger; you read better.",
        "The combat state is ephemeral: it is thrown away.",
      ],
      demande: [
        "An item of this floor's class: the biome's archetype, nothing else.",
        "Bring a word whose archetype is the band's.",
        "An item of the biome; its class is read, not declared.",
        "One item, of the occupants' class: same muse as theirs.",
        "The floor's class, in your vault; the age is nothing to me.",
        "An item whose muse is the band's: I know it by the archetype.",
        "Show a word of the house; here the house is a class.",
        "An item of this class: tragedy wants its chorus.",
        "Bring the biome's class; a capture of that class will do as well.",
      ],
      don: [
        "Sulphur: a stone turns a piece without the smith, once.",
        "Here is sulphur; transmutation is the existing craft, no more, no less.",
        "Sulphur: drunk on one floor, the effect stays there, then the vial is discarded.",
        "Take the sulphur; the turned piece's word is another word, the old one is not rewritten.",
        "Sulphur; once drunk, its word is noted and does not return.",
        "A ✚ vial; the species is the dominant floor of its glyph.",
        "Sulphur: the stone is consumed, the piece becomes another piece.",
        "Sulphur; neither the norm nor the axes are touched.",
        "Sulphur transmutes; it multiplies nothing.",
      ],
    },
  },
  mars: {
    fr: {
      accueil: [
        "T à gauche, S à droite : le préfixe n'est pas le suffixe.",
        "Trois rangs de pierre : même angle, trois axes.",
        "La pierre est consommée ; la pièce devient une autre pièce.",
        "Le mot tient en trente-deux bits : dix par composante, deux pour l'omise.",
        "Une capsule se forge d'une gemme et de sel ; elle garde le mot de la gemme.",
        "La philosophale est réservée aux dix premiers coffres, une arme, une fois.",
        "Sept armes : Lance, Faux, Arc, Lame, Fronde, Sceptre, Aiguille.",
        "Ici on tourne sans élixir ; ailleurs dans la Tour il faut le soufre.",
        "Tourner conserve la norme : le produit de deux unités est une unité.",
      ],
      demande: [
        "Une pierre et une pièce sertissable : arme, armure ou trouvaille.",
        "Apportez la pierre ; la pièce, je la tourne, je ne la garde pas.",
        "Une pierre T ou S, et une pièce qui accepte la tournure.",
        "Une gemme et du sel, si c'est une capsule que vous voulez ; la gemme y passe.",
        "Une pierre, une pièce : l'affixe dit le rang, le rang dit le générateur.",
        "Pas de gemme sur l'enclume pour tourner : la gemme s'enchâsse, la pierre tourne.",
        "Une pièce et sa pierre ; deux objets, pas trois.",
        "Apportez la pierre du rang que vous voulez : un, deux ou trois, même angle.",
        "Une pierre, une pièce ; je frappe une fois.",
      ],
      don: [
        "Tournée : nouveau mot, même norme, l'ancien n'est pas réécrit.",
        "Voilà la pièce tournée ; la pierre est consommée, l'élixir non.",
        "Je tourne sans soufre : c'est le seul privilège de la forge.",
        "Une capsule : un glyphe creux, le mot de la gemme, rien dedans.",
        "Tournée ; T·q ou q·S, selon la pierre, et ce n'est pas la même chose.",
        "La pièce est une autre pièce ; les gemmes enchâssées suivent.",
        "Forgé ; le rang de la pierre choisit l'axe, l'angle est le même.",
        "Une capsule forgée ; vide elle ne fait rien, tournez-la pour l'accorder.",
        "Tourné, une fois ; revenez avec une autre pierre.",
      ],
    },
    en: {
      accueil: [
        "T on the left, S on the right: the prefix is not the suffix.",
        "Three ranks of stone: same angle, three axes.",
        "The stone is consumed; the piece becomes another piece.",
        "The word fits in thirty-two bits: ten per component, two for the omitted one.",
        "A capsule is forged from a gem and salt; it keeps the gem's word.",
        "The philosopher's stone is reserved for the first ten vaults, one weapon, once.",
        "Seven weapons: Lance, Scythe, Bow, Blade, Sling, Sceptre, Needle.",
        "Here we turn without an elixir; elsewhere in the Tower it takes sulphur.",
        "Turning conserves the norm: the product of two units is a unit.",
      ],
      demande: [
        "A stone and a settable piece: weapon, armour or find.",
        "Bring the stone; the piece I turn, I do not keep.",
        "A T or S stone, and a piece that accepts the turn.",
        "A gem and salt, if a capsule is what you want; the gem goes into it.",
        "A stone, a piece: the affix says the rank, the rank says the generator.",
        "No gem on the anvil for turning: the gem is set, the stone turns.",
        "A piece and its stone; two items, not three.",
        "Bring the stone of the rank you want: one, two or three, same angle.",
        "A stone, a piece; I strike once.",
      ],
      don: [
        "Turned: new word, same norm, the old one is not rewritten.",
        "There is the turned piece; the stone is consumed, the elixir is not.",
        "I turn without sulphur: that is the forge's only privilege.",
        "A capsule: a hollow glyph, the gem's word, nothing inside.",
        "Turned; T·q or q·S, depending on the stone, and it is not the same thing.",
        "The piece is another piece; the set gems follow.",
        "Forged; the stone's rank picks the axis, the angle is the same.",
        "A forged capsule; empty it does nothing, turn it to tune it.",
        "Turned, once; come back with another stone.",
      ],
    },
  },
  jupiter: {
    fr: {
      accueil: [
        "Trois objets, une tenue positive : c'est un ensemble.",
        "Un ticket d'antre ouvre l'antre de sa bande, une fois.",
        "Le gardien tient l'axe du biome au seuil élite : quatre-vingt-sept centièmes.",
        "À la porte du quartier, le seuil est suprême : quatre-vingt-douze centièmes.",
        "Le duel a trois temps : orbite, parade, résonance.",
        "Une capture libérée entre dans l'ensemble ; une seule par étage.",
        "Une compagne de la classe du gardien vous dessert : choisissez.",
        "L'antre donne une gemme ou une pierre de rang trois.",
        "Un ticket usé garde son mot ; seul son palier change.",
      ],
      demande: [
        "Trois objets dont la résonance d'ensemble est tenue : plus d'accords que de heurts.",
        "Apportez trois mots ; je lis les trois paires, la somme doit être positive.",
        "Un trio tenu : deux de même classe s'annulent, prenez garde.",
        "Trois objets, tenue positive ; l'âge et le genre ne comptent pas.",
        "Un ensemble : trois voix, trois paires, une tenue.",
        "Trois mots dont les accords l'emportent ; les captures comptent aussi.",
        "Un trio qui tient ; un seul heurt peut suffire à le défaire.",
        "Trois objets ; je lis la tenue, pas le nombre.",
        "Apportez l'ensemble ; le ticket vaut pour toute la bande.",
      ],
      don: [
        "Un ticket d'antre : il ouvre l'antre de cette bande, un étage clos, un gardien.",
        "Voici le ticket ; l'antre se franchit en trois temps, sans points de vie.",
        "Ticket d'antre : repoussé, vous perdez un étage ; rien d'autre.",
        "Prenez le ticket ; le gardien tient l'axe, votre objet doit le lire.",
        "Un ticket ; au temps trois, libérez une capture, une seule, pour l'ensemble.",
        "Ticket : consommé au passage, son mot reste, son palier devient l'étage.",
        "Un ticket d'antre ; la récompense est une gemme ou une pierre de rang trois.",
        "Voici le ticket ; à la porte d'un quartier, le gardien tient au seuil suprême.",
        "Ticket d'antre : la tenue s'est lue, gardez l'ensemble pour le gardien.",
      ],
    },
    en: {
      accueil: [
        "Three items, a positive hold: that is an ensemble.",
        "A lair ticket opens the lair of its band, once.",
        "The guardian holds the biome's axis at the elite threshold: eighty-seven hundredths.",
        "At the quarter's gate, the threshold is supreme: ninety-two hundredths.",
        "The duel has three beats: orbit, parry, resonance.",
        "A released capture joins the ensemble; only one per floor.",
        "A companion of the guardian's class works against you: choose.",
        "The lair gives a gem or a rank-three stone.",
        "A spent ticket keeps its word; only its tier changes.",
      ],
      demande: [
        "Three items whose ensemble resonance holds: more accords than clashes.",
        "Bring three words; I read the three pairs, the sum must be positive.",
        "A held trio: two of the same class cancel out, take care.",
        "Three items, positive hold; age and kind do not count.",
        "An ensemble: three voices, three pairs, one hold.",
        "Three words whose accords prevail; captures count too.",
        "A trio that holds; a single clash can be enough to undo it.",
        "Three items; I read the hold, not the number.",
        "Bring the ensemble; the ticket is good for the whole band.",
      ],
      don: [
        "A lair ticket: it opens the lair of this band, a closed floor, one guardian.",
        "Here is the ticket; the lair is crossed in three beats, without hit points.",
        "Lair ticket: pushed back, you lose one floor; nothing else.",
        "Take the ticket; the guardian holds the axis, your item must read it.",
        "A ticket; on beat three, release a capture, only one, for the ensemble.",
        "Ticket: consumed on passing, its word remains, its tier becomes the floor.",
        "A lair ticket; the reward is a gem or a rank-three stone.",
        "Here is the ticket; at a quarter's gate, the guardian holds at the supreme threshold.",
        "Lair ticket: the hold was read, keep the ensemble for the guardian.",
      ],
    },
  },
  saturne: {
    fr: {
      accueil: [
        "Un sceau se trouve, il ne s'achète pas.",
        "Trois portes : soixante-quatre, cent vingt-huit, cent quatre-vingt-douze.",
        "Chaque porte veut le sceau de son âge exact ; un âge n'en vaut pas un autre.",
        "La mise d'un sceau : Kali deux virgule dix, Satya trente-trois virgule cinquante-cinq.",
        "Deux étages de même orbite sont en écho ; montez-les dans l'ordre, sans redescendre.",
        "Vingt et une cellules : trois classes, sept régimes.",
        "Une cellule remplie, un hymne de plus.",
        "Le coffre d'atelier passe les portes : démonstration, pas droit.",
        "Les figures ne sont pas des preuves ; un sceau, lui, se juge contre la racine signée.",
      ],
      demande: [
        "Un sceau de l'âge de ce quartier : une relique du monde, récupérée vers ce coffre.",
        "Montrez le sceau du quartier ; l'âge exact, pas un autre.",
        "Une relique récupérée, de cet âge, vers une adresse à vous.",
        "Le sceau de l'âge courant ; sans lui je ne révèle rien.",
        "Un sceau : je lis les reliques du monde, celles dont le retour est à vous.",
        "Apportez le sceau de l'âge où nous sommes ; les autres quartiers ont le leur.",
        "Un sceau de cet âge ; la mise, le nœud l'a déjà jugée.",
        "Le sceau du quartier ; en atelier, la simulation en tient lieu.",
        "Un sceau, de l'âge d'ici : c'est la clé de mes hymnes.",
      ],
      don: [
        "Les échos du quartier : les paires d'étages de même orbite, dans l'ordre à monter.",
        "Voici les échos ; montez le bas puis le haut, sans redescendre, et le mercure vient.",
        "Les échos : même orbite exacte des coupes, rien n'est arrondi ici.",
        "Je révèle les échos ; les parcourir donne un élixir de mercure, une fois par paire.",
        "Les échos du quartier ; le premier étage de la paire d'abord, toujours.",
        "Voici la liste ; un écho se lit sans rien tirer au sort.",
        "Les échos ; et un hymne par cellule de votre bestiaire remplie.",
        "Échos révélés ; vingt et une cellules pleines, et l'astronome vous lira les cent une formes.",
        "Les échos du quartier ; la porte suivante veut un autre âge.",
      ],
    },
    en: {
      accueil: [
        "A seal is found, never bought.",
        "Three gates: sixty-four, one hundred twenty-eight, one hundred ninety-two.",
        "Each gate wants the seal of its exact age; one age is not worth another.",
        "A seal's stake: Kali two point ten, Satya thirty-three point fifty-five.",
        "Two floors of the same orbit are in echo; climb them in order, without descending.",
        "Twenty-one cells: three classes, seven regimes.",
        "A filled cell, one more hymn.",
        "The workshop vault passes the gates: demonstration, not right.",
        "Figures are not proofs; a seal, though, is judged against the signed root.",
      ],
      demande: [
        "A seal of this quarter's age: a world relic, recovered to this vault.",
        "Show the quarter's seal; the exact age, no other.",
        "A recovered relic, of this age, to an address of yours.",
        "The seal of the current age; without it I reveal nothing.",
        "A seal: I read the world's relics, those whose return is yours.",
        "Bring the seal of the age we stand in; the other quarters have their own.",
        "A seal of this age; the stake, the node has already judged.",
        "The quarter's seal; in the workshop, the simulation stands in for it.",
        "A seal, of this age: it is the key to my hymns.",
      ],
      don: [
        "The quarter's echoes: the pairs of floors of the same orbit, in climbing order.",
        "Here are the echoes; climb the low one then the high one, without descending, and mercury comes.",
        "The echoes: exact same orbit of the slices, nothing is rounded here.",
        "I reveal the echoes; walking them gives a mercury elixir, once per pair.",
        "The quarter's echoes; the pair's first floor first, always.",
        "Here is the list; an echo is read without drawing lots.",
        "The echoes; and one hymn per filled cell of your bestiary.",
        "Echoes revealed; twenty-one full cells, and the astronomer will read you the hundred and one forms.",
        "The quarter's echoes; the next gate wants another age.",
      ],
    },
  },
  uranie: {
    fr: {
      accueil: [
        "La tête signée dit la hauteur, le validateur, la racine : de quoi juger sans rejouer.",
        "Sept validateurs, un créneau par heure, rotation de pas trois.",
        "Un nombre de validateurs divisible par trois est refusé.",
        "La récompense ne se divise jamais : elle suit un cosinus, a plus a demi fois cos.",
        "Quatre âges, soixante-deux millions huit cent quatre-vingt-dix-neuf mille deux cents eidôla en tout.",
        "Un eidôlon vaut cent millions d'atomes.",
        "Ici rien n'est donné : on lit.",
        "Deux cent cinquante-cinq coupes, une seule norme : dix puissance huit.",
        "L'observatoire est la seule fenêtre de la Tour sur la chaîne, et elle reste une lecture.",
      ],
      demande: [
        "Je ne demande rien ; suivez le réseau, je lirai sa tête.",
        "Rien : la tête du réseau se lit depuis etat.json, vérifiée à la lecture, jamais persistée.",
        "Aucune demande ; les reliques du monde et leur statut, je les lis aussi.",
        "Rien ; le nombre d'étages honorés par votre coffre, je le compte, c'est tout.",
        "Je ne veux rien : le cosinus est calculé en décimal, jamais en flottant.",
        "Rien à donner, rien à demander ; deux nœuds, deux libm, ce serait une scission.",
        "Aucune demande ; le proposant du créneau s est V de trois s modulo n.",
        "Rien ; l'énergie est bornée par le consensus, pas par le travail.",
        "Je ne demande rien ; le bloc porte sa racine, et la racine se recalcule.",
      ],
      don: [
        "Lecture : la tête signée, la racine UTXO, le validateur du dernier bloc.",
        "Je lis, je ne donne pas : hauteur, validateur, racine ; jugez.",
        "Lecture des reliques du monde : attente, intacte, récupérée ; aucune graine ici.",
        "Vos étages honorés, comptés ; la Tour n'y ajoute aucune puissance.",
        "Vingt et une cellules pleines : je lis les cent une formes, et celles que vous avez rencontrées.",
        "Une lecture : le bloc suivant paiera a plus a demi cos, à l'atome près.",
        "Lecture : chaque époque somme exactement a fois T, par plus fort reste.",
        "Je lis la fédération : sept racines XMSS, quatre mille quatre-vingt-seize signatures chacune.",
        "Lecture, puis silence : le faîte ne donne rien, il montre.",
      ],
    },
    en: {
      accueil: [
        "The signed head states the height, the validator, the root: enough to judge without replaying.",
        "Seven validators, one slot per hour, rotation of step three.",
        "A number of validators divisible by three is refused.",
        "The reward never divides: it follows a cosine, a plus half a times cos.",
        "Four ages, sixty-two million eight hundred ninety-nine thousand two hundred eidola in all.",
        "One eidolon is one hundred million atoms.",
        "Here nothing is given: we read.",
        "Two hundred fifty-five slices, a single norm: ten to the eighth.",
        "The observatory is the Tower's only window on the chain, and it stays a reading.",
      ],
      demande: [
        "I ask for nothing; follow the network, I will read its head.",
        "Nothing: the network head is read from etat.json, verified on reading, never persisted.",
        "No request; the world's relics and their status, I read them too.",
        "Nothing; the number of floors your vault has honoured, I count it, that is all.",
        "I want nothing: the cosine is computed in decimal, never in floating point.",
        "Nothing to give, nothing to ask; two nodes, two libm, that would be a split.",
        "No request; the proposer of slot s is V of three s modulo n.",
        "Nothing; energy is bounded by consensus, not by work.",
        "I ask for nothing; the block carries its root, and the root is recomputed.",
      ],
      don: [
        "Reading: the signed head, the UTXO root, the validator of the last block.",
        "I read, I do not give: height, validator, root; judge.",
        "Reading of the world's relics: waiting, intact, recovered; no seed here.",
        "Your honoured floors, counted; the Tower adds no power to them.",
        "Twenty-one full cells: I read the hundred and one forms, and those you have met.",
        "A reading: the next block will pay a plus half a cos, to the atom.",
        "Reading: every epoch sums exactly a times T, by largest remainder.",
        "I read the federation: seven XMSS roots, four thousand ninety-six signatures each.",
        "Reading, then silence: the peak gives nothing, it shows.",
      ],
    },
  },
};

/** 12 noms par muse : noms communs, une jauge ; l'identité reste le mot. */
export const NOMS_CAPTURE: Record<SignatureId, readonly string[]> = {
  terre: [
    "Chthon",
    "Pelos",
    "Humus",
    "Gleba",
    "Talpa",
    "Motte",
    "Silex",
    "Ocre",
    "Tuf",
    "Loess",
    "Marne",
    "Argile",
  ],
  lune: [
    "Mnème",
    "Codex",
    "Stèle",
    "Annale",
    "Glose",
    "Folio",
    "Onciale",
    "Colophon",
    "Signet",
    "Palimpseste",
    "Rubrique",
    "Cartulaire",
  ],
  mercure: [
    "Vif",
    "Alambic",
    "Athanor",
    "Cinabre",
    "Fiole",
    "Retorte",
    "Cornue",
    "Aludel",
    "Pélican",
    "Serpentin",
    "Amalgame",
    "Sublimé",
  ],
  venus: [
    "Volte",
    "Ronde",
    "Pavane",
    "Gigue",
    "Sarabande",
    "Courante",
    "Bourrée",
    "Farandole",
    "Tarentelle",
    "Passacaille",
    "Gavotte",
    "Allemande",
  ],
  soleil: [
    "Cothurne",
    "Masque",
    "Chœur",
    "Parodos",
    "Stasimon",
    "Exodos",
    "Péplos",
    "Coryphée",
    "Thymélé",
    "Skéné",
    "Orchestra",
    "Kommos",
  ],
  mars: [
    "Enclume",
    "Tenaille",
    "Soufflet",
    "Braise",
    "Scorie",
    "Laitier",
    "Trempe",
    "Étampe",
    "Mandrin",
    "Bigorne",
    "Chasse",
    "Tranche",
  ],
  jupiter: [
    "Aulos",
    "Syrinx",
    "Lyre",
    "Cithare",
    "Tympanon",
    "Sistre",
    "Crotale",
    "Plectre",
    "Chalumeau",
    "Bourdon",
    "Anche",
    "Pavillon",
  ],
  saturne: [
    "Antienne",
    "Tropaire",
    "Répons",
    "Verset",
    "Litanie",
    "Cantique",
    "Séquence",
    "Prosodie",
    "Neume",
    "Mélisme",
    "Ison",
    "Ténor",
  ],
  uranie: [
    "Astrolabe",
    "Armille",
    "Quadrant",
    "Sextant",
    "Alidade",
    "Gnomon",
    "Épicycle",
    "Déférent",
    "Nadir",
    "Zénith",
    "Apogée",
    "Périgée",
  ],
};

export function repliquesDe(
  muse: SignatureId,
  langue: LangueHote,
  groupe: GroupeReplique,
): readonly string[] {
  return REPLIQUES[muse][langue][groupe];
}

export function nomCapture(muse: SignatureId, indice: number): string {
  const noms = NOMS_CAPTURE[muse];
  return noms[((indice % noms.length) + noms.length) % noms.length]!;
}
