/**
 * Les 64 œufs de la Chambre de Genèse — données figées, transposées du dossier
 * Eidolon (janvier 2026) : index, ère, nom d'ère (traduit), thème, forme de
 * manifestation, essence. Ne pas éditer à la main : `gen_oeufs.py` les tire du
 * dossier d'origine. Aucune statistique, aucune puissance : une lecture.
 */

export type ThemeOeuf =
  "void" | "quantum" | "temporal" | "spatial" | "entropic" | "harmonic" | "celestial" | "spinorial";

export type OeufData = {
  readonly index: number;
  readonly ere: number;
  readonly nomEre: { readonly fr: string; readonly en: string };
  readonly theme: ThemeOeuf;
  readonly forme: string;
  readonly essence: string;
};

export const OEUFS_DATA: readonly OeufData[] = [
  {
    index: 0,
    ere: 1,
    nomEre: { fr: "Ère du Vide primordial", en: "Era of Primordial Void" },
    theme: "void",
    forme: "void_consciousness",
    essence: "primordial_void",
  },
  {
    index: 1,
    ere: 2,
    nomEre: { fr: "Ère de l'Aube abyssale", en: "Era of Abyssal Dawn" },
    theme: "void",
    forme: "null_being",
    essence: "primordial_void",
  },
  {
    index: 2,
    ere: 3,
    nomEre: { fr: "Ère des Ténèbres silencieuses", en: "Era of Silent Darkness" },
    theme: "void",
    forme: "void_consciousness",
    essence: "primordial_void",
  },
  {
    index: 3,
    ere: 4,
    nomEre: { fr: "Ère de l'Éveil nul", en: "Era of Null Awakening" },
    theme: "void",
    forme: "primordial_dragon",
    essence: "primordial_void",
  },
  {
    index: 4,
    ere: 5,
    nomEre: { fr: "Ère de la Maîtrise du Vide", en: "Era of Void Mastery" },
    theme: "void",
    forme: "null_being",
    essence: "primordial_void",
  },
  {
    index: 5,
    ere: 6,
    nomEre: { fr: "Ère du Trône vide", en: "Era of Empty Throne" },
    theme: "void",
    forme: "primordial_dragon",
    essence: "primordial_void",
  },
  {
    index: 6,
    ere: 7,
    nomEre: { fr: "Ère du Silence final", en: "Era of Final Silence" },
    theme: "void",
    forme: "primordial_dragon",
    essence: "primordial_void",
  },
  {
    index: 7,
    ere: 8,
    nomEre: { fr: "Ère de la Naissance quantique", en: "Era of Quantum Birth" },
    theme: "void",
    forme: "abyssal_entity",
    essence: "primordial_void",
  },
  {
    index: 8,
    ere: 9,
    nomEre: { fr: "Ère de la Superposition", en: "Era of Superposition" },
    theme: "quantum",
    forme: "quantum_waveform",
    essence: "quantum_potential",
  },
  {
    index: 9,
    ere: 10,
    nomEre: { fr: "Ère des Esprits intriqués", en: "Era of Entangled Minds" },
    theme: "quantum",
    forme: "superposition_entity",
    essence: "quantum_potential",
  },
  {
    index: 10,
    ere: 11,
    nomEre: { fr: "Ère de l'Effondrement de l'onde", en: "Era of Wave Collapse" },
    theme: "quantum",
    forme: "probability_dragon",
    essence: "quantum_potential",
  },
  {
    index: 11,
    ere: 12,
    nomEre: { fr: "Ère de la Tempête de probabilités", en: "Era of Probability Storm" },
    theme: "quantum",
    forme: "entanglement_beast",
    essence: "quantum_potential",
  },
  {
    index: 12,
    ere: 13,
    nomEre: { fr: "Ère des Chemins incertains", en: "Era of Uncertain Paths" },
    theme: "quantum",
    forme: "quantum_waveform",
    essence: "quantum_potential",
  },
  {
    index: 13,
    ere: 14,
    nomEre: { fr: "Ère de la Maîtrise quantique", en: "Era of Quantum Mastery" },
    theme: "quantum",
    forme: "entanglement_beast",
    essence: "quantum_potential",
  },
  {
    index: 14,
    ere: 15,
    nomEre: { fr: "Ère du Premier Instant", en: "Era of First Moment" },
    theme: "quantum",
    forme: "probability_dragon",
    essence: "quantum_potential",
  },
  {
    index: 15,
    ere: 16,
    nomEre: { fr: "Ère du Flux temporel", en: "Era of Temporal Flow" },
    theme: "quantum",
    forme: "probability_dragon",
    essence: "quantum_potential",
  },
  {
    index: 16,
    ere: 17,
    nomEre: { fr: "Ère de la Trame chronologique", en: "Era of Chrono Weave" },
    theme: "temporal",
    forme: "time_monolith",
    essence: "temporal_flow",
  },
  {
    index: 17,
    ere: 18,
    nomEre: { fr: "Ère du Paradoxe levant", en: "Era of Paradox Rising" },
    theme: "temporal",
    forme: "time_monolith",
    essence: "temporal_flow",
  },
  {
    index: 18,
    ere: 19,
    nomEre: { fr: "Ère de l'Éternel Présent", en: "Era of Eternal Now" },
    theme: "temporal",
    forme: "temporal_paradox",
    essence: "temporal_flow",
  },
  {
    index: 19,
    ere: 20,
    nomEre: { fr: "Ère de la Maîtrise du Temps", en: "Era of Time Mastery" },
    theme: "temporal",
    forme: "time_monolith",
    essence: "temporal_flow",
  },
  {
    index: 20,
    ere: 21,
    nomEre: { fr: "Ère de la Dernière Seconde", en: "Era of Last Second" },
    theme: "temporal",
    forme: "chrono_entity",
    essence: "temporal_flow",
  },
  {
    index: 21,
    ere: 22,
    nomEre: { fr: "Ère de la Faille dimensionnelle", en: "Era of Dimensional Rift" },
    theme: "temporal",
    forme: "time_monolith",
    essence: "temporal_flow",
  },
  {
    index: 22,
    ere: 23,
    nomEre: { fr: "Ère du Pli spatial", en: "Era of Spatial Fold" },
    theme: "temporal",
    forme: "chrono_entity",
    essence: "temporal_flow",
  },
  {
    index: 23,
    ere: 24,
    nomEre: { fr: "Ère de l'Espace infini", en: "Era of Infinite Space" },
    theme: "temporal",
    forme: "chrono_entity",
    essence: "temporal_flow",
  },
  {
    index: 24,
    ere: 25,
    nomEre: { fr: "Ère de la Tempête vectorielle", en: "Era of Vector Storm" },
    theme: "spatial",
    forme: "dimensional_fold",
    essence: "spatial_matrix",
  },
  {
    index: 25,
    ere: 26,
    nomEre: { fr: "Ère des Rêves de variété", en: "Era of Manifold Dreams" },
    theme: "spatial",
    forme: "manifold_consciousness",
    essence: "spatial_matrix",
  },
  {
    index: 26,
    ere: 27,
    nomEre: { fr: "Ère de la Maîtrise de l'Espace", en: "Era of Space Mastery" },
    theme: "spatial",
    forme: "space_entity",
    essence: "spatial_matrix",
  },
  {
    index: 27,
    ere: 28,
    nomEre: { fr: "Ère de la Dimension finale", en: "Era of Final Dimension" },
    theme: "spatial",
    forme: "dimensional_fold",
    essence: "spatial_matrix",
  },
  {
    index: 28,
    ere: 29,
    nomEre: { fr: "Ère de la Naissance de l'entropie", en: "Era of Entropy Birth" },
    theme: "spatial",
    forme: "space_entity",
    essence: "spatial_matrix",
  },
  {
    index: 29,
    ere: 30,
    nomEre: { fr: "Ère du Chaos levant", en: "Era of Chaos Rising" },
    theme: "spatial",
    forme: "vector_being",
    essence: "spatial_matrix",
  },
  {
    index: 30,
    ere: 31,
    nomEre: { fr: "Ère de la Danse du désordre", en: "Era of Disorder Dance" },
    theme: "spatial",
    forme: "dimensional_fold",
    essence: "spatial_matrix",
  },
  {
    index: 31,
    ere: 32,
    nomEre: { fr: "Ère du Sort aléatoire", en: "Era of Random Fate" },
    theme: "spatial",
    forme: "manifold_consciousness",
    essence: "spatial_matrix",
  },
  {
    index: 32,
    ere: 33,
    nomEre: { fr: "Ère de la Floraison du déclin", en: "Era of Decay Bloom" },
    theme: "entropic",
    forme: "chaos_entity",
    essence: "entropic_chaos",
  },
  {
    index: 33,
    ere: 34,
    nomEre: { fr: "Ère de la Maîtrise de l'entropie", en: "Era of Entropy Mastery" },
    theme: "entropic",
    forme: "entropy_manifestation",
    essence: "entropic_chaos",
  },
  {
    index: 34,
    ere: 35,
    nomEre: { fr: "Ère du Chaos ultime", en: "Era of Ultimate Chaos" },
    theme: "entropic",
    forme: "chaos_entity",
    essence: "entropic_chaos",
  },
  {
    index: 35,
    ere: 36,
    nomEre: { fr: "Ère de la Première Résonance", en: "Era of First Resonance" },
    theme: "entropic",
    forme: "randomness_being",
    essence: "entropic_chaos",
  },
  {
    index: 36,
    ere: 37,
    nomEre: { fr: "Ère de l'Onde harmonique", en: "Era of Harmonic Wave" },
    theme: "entropic",
    forme: "entropy_manifestation",
    essence: "entropic_chaos",
  },
  {
    index: 37,
    ere: 38,
    nomEre: { fr: "Ère du Décalage de fréquence", en: "Era of Frequency Shift" },
    theme: "entropic",
    forme: "disorder_dragon",
    essence: "entropic_chaos",
  },
  {
    index: 38,
    ere: 39,
    nomEre: { fr: "Ère de l'Accord cosmique", en: "Era of Cosmic Chord" },
    theme: "entropic",
    forme: "disorder_dragon",
    essence: "entropic_chaos",
  },
  {
    index: 39,
    ere: 40,
    nomEre: { fr: "Ère de la Symphonie levante", en: "Era of Symphony Rise" },
    theme: "entropic",
    forme: "randomness_being",
    essence: "entropic_chaos",
  },
  {
    index: 40,
    ere: 41,
    nomEre: { fr: "Ère de la Maîtrise harmonique", en: "Era of Harmonic Mastery" },
    theme: "harmonic",
    forme: "resonance_entity",
    essence: "harmonic_resonance",
  },
  {
    index: 41,
    ere: 42,
    nomEre: { fr: "Ère du Ton parfait", en: "Era of Perfect Tone" },
    theme: "harmonic",
    forme: "frequency_being",
    essence: "harmonic_resonance",
  },
  {
    index: 42,
    ere: 43,
    nomEre: { fr: "Ère de la Naissance stellaire", en: "Era of Stellar Birth" },
    theme: "harmonic",
    forme: "harmonic_wave",
    essence: "harmonic_resonance",
  },
  {
    index: 43,
    ere: 44,
    nomEre: { fr: "Ère de l'Éclat de nova", en: "Era of Nova Burst" },
    theme: "harmonic",
    forme: "frequency_being",
    essence: "harmonic_resonance",
  },
  {
    index: 44,
    ere: 45,
    nomEre: { fr: "Ère du Rêve de nébuleuse", en: "Era of Nebula Dream" },
    theme: "harmonic",
    forme: "resonance_entity",
    essence: "harmonic_resonance",
  },
  {
    index: 45,
    ere: 46,
    nomEre: { fr: "Ère de la Marée galactique", en: "Era of Galactic Tide" },
    theme: "harmonic",
    forme: "harmonic_wave",
    essence: "harmonic_resonance",
  },
  {
    index: 46,
    ere: 47,
    nomEre: { fr: "Ère de la Forge des étoiles", en: "Era of Star Forge" },
    theme: "harmonic",
    forme: "harmonic_wave",
    essence: "harmonic_resonance",
  },
  {
    index: 47,
    ere: 48,
    nomEre: { fr: "Ère de la Maîtrise céleste", en: "Era of Celestial Mastery" },
    theme: "harmonic",
    forme: "cosmic_chord",
    essence: "harmonic_resonance",
  },
  {
    index: 48,
    ere: 49,
    nomEre: { fr: "Ère de l'Aube cosmique", en: "Era of Cosmic Dawn" },
    theme: "celestial",
    forme: "cosmos_manifestation",
    essence: "celestial_light",
  },
  {
    index: 49,
    ere: 50,
    nomEre: { fr: "Ère de la Première Géométrie", en: "Era of First Geometry" },
    theme: "celestial",
    forme: "galactic_being",
    essence: "celestial_light",
  },
  {
    index: 50,
    ere: 51,
    nomEre: { fr: "Ère de la Torsion spinorielle", en: "Era of Spinor Twist" },
    theme: "celestial",
    forme: "cosmos_manifestation",
    essence: "celestial_light",
  },
  {
    index: 51,
    ere: 52,
    nomEre: { fr: "Ère des Forges des éléments", en: "Era of Element Forges" },
    theme: "celestial",
    forme: "cosmos_manifestation",
    essence: "celestial_light",
  },
  {
    index: 52,
    ere: 53,
    nomEre: { fr: "Ère de la Formation galactique", en: "Era of Galactic Formation" },
    theme: "celestial",
    forme: "star_entity",
    essence: "celestial_light",
  },
  {
    index: 53,
    ere: 54,
    nomEre: { fr: "Ère de la Genèse planétaire", en: "Era of Planetary Genesis" },
    theme: "celestial",
    forme: "star_entity",
    essence: "celestial_light",
  },
  {
    index: 54,
    ere: 55,
    nomEre: { fr: "Ère de l'Allumage de la vie", en: "Era of Life Ignition" },
    theme: "celestial",
    forme: "galactic_being",
    essence: "celestial_light",
  },
  {
    index: 55,
    ere: 56,
    nomEre: { fr: "Ère de l'Aube consciente", en: "Era of Conscious Dawn" },
    theme: "celestial",
    forme: "cosmos_manifestation",
    essence: "celestial_light",
  },
  {
    index: 56,
    ere: 57,
    nomEre: { fr: "Ère des Premières Formes", en: "Era of First Forms" },
    theme: "spinorial",
    forme: "geometric_consciousness",
    essence: "spinorial_geometry",
  },
  {
    index: 57,
    ere: 58,
    nomEre: { fr: "Ère des Solides platoniciens", en: "Era of Platonic Solids" },
    theme: "spinorial",
    forme: "spinor_entity",
    essence: "spinorial_geometry",
  },
  {
    index: 58,
    ere: 59,
    nomEre: { fr: "Ère de la Suite de Fibonacci", en: "Era of Fibonacci Sequence" },
    theme: "spinorial",
    forme: "geometric_consciousness",
    essence: "spinorial_geometry",
  },
  {
    index: 59,
    ere: 60,
    nomEre: { fr: "Ère de l'Aube fractale", en: "Era of Fractal Dawn" },
    theme: "spinorial",
    forme: "geometric_consciousness",
    essence: "spinorial_geometry",
  },
  {
    index: 60,
    ere: 61,
    nomEre: { fr: "Ère des Lois mathématiques", en: "Era of Mathematical Laws" },
    theme: "spinorial",
    forme: "geometric_consciousness",
    essence: "spinorial_geometry",
  },
  {
    index: 61,
    ere: 62,
    nomEre: { fr: "Ère de la Brisure de symétrie", en: "Era of Symmetry Breaking" },
    theme: "spinorial",
    forme: "spinor_entity",
    essence: "spinorial_geometry",
  },
  {
    index: 62,
    ere: 63,
    nomEre: { fr: "Ère de la Conscience géométrique", en: "Era of Geometric Consciousness" },
    theme: "spinorial",
    forme: "tensor_manifestation",
    essence: "spinorial_geometry",
  },
  {
    index: 63,
    ere: 64,
    nomEre: { fr: "Ère du Champ unifié", en: "Era of Unified Field" },
    theme: "spinorial",
    forme: "geometric_consciousness",
    essence: "spinorial_geometry",
  },
];
